### PR TITLE
feat(tier4_planning_msgs): add allow_while_using_route

### PR DESCRIPTION
**Pull request by kosuke55**
## Related Links

- used in https://github.com/autowarefoundation/autoware.universe/pull/9200 

## Description

add allow_while_using_route to internal mesgs

https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/features/routing/#allow_while_using_route

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code is properly formatted
- [x] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Comment by isamu-takagi** [comment]
@mitsudome-r @yukkysaito Could you please merge this PR?

**Comment by yukkysaito** [comment]
I don't quite understand the background here; could you explain it to me?

**Comment by isamu-takagi** [comment]
@yukkysaito This is because there was a request to change the route only when it is not in use, so that it does not affect the behavior of the vehicle.

**Comment by isamu-takagi** [comment]
@mitsudome-r @yukkysaito friendly ping.

**Review by yukkysaito — CHANGES_REQUESTED** [review]
Based on internal discussions, it was decided that further discussion is needed. with @isamu-takagi @mitsudome-r

**Comment by isamu-takagi** [comment]
I will close it for now.

**Comment by kosuke55** [comment]
I did not catch up but ok thanks for discussion

**Pull request closed without merging**
