### PR TITLE
feat(tier4_rtc_msgs): add CooperateCommands

### PR DESCRIPTION
**Pull request by tkhmy**
Signed-off-by: tkhmy <tkh.my.p@gmail.com>

## Description

Add CooperateCommands definition files for request to cooperate.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by rej55 — COMMENTED** [review]
Thank you for your contribution!
If we use `CooperateCommands.srv` in general, don't we need `CooperateCommand.srv` ?
I think it is okay to remove `CooperateCommand.srv`.

**Comment by tkhmy** [comment]
> Thank you for your contribution! If we use `CooperateCommands.srv` in general, don't we need `CooperateCommand.srv` ? I think it is okay to remove `CooperateCommand.srv`.

Thanks. @rej55  I think the  `CooperateCommand.srv` is still needed for the adaptor to send the request to the autoware. The `CooperateCommands.srv`  is used when we want to send multiple commends to the adaptor. 

How do you think?

**Comment by rej55** [comment]
I think it is okay to use `CooperateCommands.srv` instead of `CooperateCommand.srv`.
My concern is that we may confuse `CooperateCommand.srv` with `CooperateCommand.msg`.

**Comment by isamu-takagi** [comment]
@tkhmy @rej55 

In the first design, API receives CooperateCommands.srv, and send CooperateCommand.srv to Autoware moculdes with type conversion. But @rej55 says Autoware modules can use CooperateCommands.srv instead of CooperateCommand.srv.

In this case CooperateCommand.srv is no longer needed. API does not need type conversion. The API adaptor convert one CooperateCommands.srv to multiple CooperateCommands by filtering by module.

**Comment by tkhmy** [comment]
@rej55 @isamu-takagi 
Removed the `CooperateCommand.srv`

**Comment by isamu-takagi** [comment]
These messages are always used together. Should we combine them?
```
unique_identifier_msgs/UUID uuid
tier4_rtc_msgs/Module module
```

**Comment by tkhmy** [comment]
> These messages are always used together. Should we combine them?
> 
> ```
> unique_identifier_msgs/UUID uuid
> tier4_rtc_msgs/Module module
> ```

I think it should be separated like now because if the uuid belongs to module, we will need to go into the module to check the uuid.

In `CooperateStatus` the uuid refer to the whole msg, so I think should remain the same.

**Comment by tkhmy** [comment]
@isamu-takagi @rej55 
Hi, is this PR okay for review?

**Review by rej55 — APPROVED** [review]
LGTM

**Pull request merged**
