### PR TITLE
Add detected object with feature (#54) (#59)

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Related Links

- add following msgs
- DetectedObjectWithFeature 
- DetectedObjectsWithFeature

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by satoshi-ota** [comment]
@isamu-takagi @kenji-miyake 

Do we need to pick up the following PR to resolve the CI/CD error ? :thinking: 

- https://github.com/tier4/AutowareArchitectureProposal_msgs/pull/2

**Comment by satoshi-ota** [comment]
> @isamu-takagi @kenji-miyake
> 
> Do we need to pick up the following PR to resolve the CI/CD error ? thinking
> 
> * [Fix build_depends.repos #2](https://github.com/tier4/AutowareArchitectureProposal_msgs/pull/2)

fix in https://github.com/tier4/AutowareArchitectureProposal_msgs/pull/4/commits/9fe5f15b722a90d691152b33f526ab208165bcb7

pass all CI/CD :smile:

**Comment by kenji-miyake** [comment]
@satoshi-ota Nice work! But I think you should change the target branch.

**Comment by satoshi-ota** [comment]
@kenji-miyake Ok, witch branch would be appropriate? Do I have to make use-autoware-auto-msgs in this repo, too?

**Comment by kenji-miyake** [comment]
@satoshi-ota Yes, it's fine. FYI the reason is `main` is reserved for syncing with the internal repository.

**Comment by satoshi-ota** [comment]
@kenji-miyake I see :+1: 
I'll create `use-autoware-auto-msgs` branch in this repo, and update the build depends in AutowareArchitectureProposal.iv.

https://github.com/tier4/AutowareArchitectureProposal.iv/blob/449209219cb3b1d3fbf153c8bc639f6d9b65e985/build_depends.repos#L2-L5

**Comment by kenji-miyake** [comment]
@satoshi-ota Perfect!

**Comment by satoshi-ota** [comment]
update target branch :+1:

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
