### PR TITLE
feat(tier4_vehicle_msgs): add new msgs for engage-on-driving

### PR DESCRIPTION
**Pull request by TakaHoribe**
## Description

Add new messages for engage-on-driving function

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [x] All open points are addressed and tracked via issues or tickets
- [x] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by TakaHoribe** [comment]
Note: OperationMode should be in higher-level message, e.g. tier4_system_msgs

**Comment by TakaHoribe** [comment]
I put OperationMode.msg in tier4_system_msg for the global use in api/control/vehicle etc.

@yukkysaito @isamu-takagi 
I still have a concern: NONE/DIRECT/LOCAL is a little confusing. Any suggestions are welcome.

**Comment by TakaHoribe** [comment]
@isamu-takagi I feel like NONE state can be merged in MANUAL. What is the reason why we need the NONE state?

**Comment by yukkysaito** [comment]
>I still have a concern: NONE/DIRECT/LOCAL is a little confusing. Any suggestions are welcome.

@TakaHoribe 
umm...
DIRECT -> `DRIVER`
LOCAL -> `LOCAL MANUAL CONTROLLER` or `LOCAL MANUAL CONTROL DRIVER`
REMOTE-> `REMOTE MANUAL CONTROLLER` or `REMOTE MANUAL CONTROL DRIVER`
how about this? too long name?

**Comment by isamu-takagi** [comment]
> I feel like NONE state can be merged in MANUAL. What is the reason why we need the NONE state?

For example, startup of a vehicle without direct mode. At this time, it is not in direct mode because the vehicle does not support it. And the local/remote operator is not ready and it is not in autonomous. So a mode to stop is needed.

**Comment by isamu-takagi** [comment]
> I still have a concern: NONE/DIRECT/LOCAL is a little confusing. Any suggestions are welcome.

For `LOCAL` and `REMOTE`, how about `LOCAL_OPERATOR` or `LOCAL_COMMAND`?

**Comment by TakaHoribe** [comment]
@yukkysaito @isamu-takagi 

> For example, startup of a vehicle without direct mode. At this time, it is not in direct mode because the vehicle does not support it. And the local/remote operator is not ready and it is not in autonomous. So a mode to stop is needed.

I understand the NONE state represents the case of "any operators/systems are not ready". However, it still has ambiguity in the responsibility. How about INITIALIZING or something more specific? 

> For LOCAL and REMOTE, how about LOCAL_OPERATOR or LOCAL_COMMAND?

So, like this?

```
NONE
DIRECT
REMOTE     ->     REMOTE_OPERATOR
LOCAL      ->     LOCAL_OPERATOR
TRANSITION_TO_AUTO
AUTONOMOUS
```

Or how about:

```
NONE
DIRECT     ->     MANUAL_DIRECT
REMOTE     ->     MANUAL_REMOTE
LOCAL      ->     MANUAL_LOCAL
TRANSITION_TO_AUTO
AUTONOMOUS
```

**Comment by yukkysaito** [comment]
I like this. About `REMOTE` and `LOCAL`, the manual is true from view of the autonomous driving system. But from the point of view vehicle, it is part of the autonomous driving system and not manual.
So, sometimes `MANUAL_REMOTE` may mislead.
```
NONE
DIRECT     ->     MANUAL_DIRECT
REMOTE     ->     REMOTE_OPERATOR
LOCAL      ->     LOCAL_OPERATOR
TRANSITION_TO_AUTO
AUTONOMOUS
```

**Comment by TakaHoribe** [comment]
>NONE
DIRECT     ->     MANUAL_DIRECT
REMOTE     ->     REMOTE_OPERATOR
LOCAL      ->     LOCAL_OPERATOR
TRANSITION_TO_AUTO
AUTONOMOUS

@yukkysaito @isamu-takagi 

Looks good to me. 
Could we align with [adapi_msg](https://tier4.github.io/autoware-documentation/pr-7/design/autoware-interfaces/ad-api/features/operation-mode/)?

**Comment by TakaHoribe** [comment]
Fix to:

```
uint8 STOP = 0                # no operation (e.g. no human driver, no autonomous system)
uint8 MANUAL_DIRECT = 1       # operated manually by a human driver
uint8 REMOTE_OPERATOR = 2     # operated manually by remote control through Autoware
uint8 LOCAL_OPERATOR = 3      # operated manually by local control (e.g. joystick) through Autoware
uint8 TRANSITION_TO_AUTO = 4  # on transition from manual to auto
uint8 AUTONOMOUS = 5 
```

with adapi

**Comment by yukkysaito** [comment]
@TakaHoribe What is the reason to be STOP instead of NONE?

**Review by isamu-takagi — APPROVED** [review]

**Comment by TakaHoribe** [comment]
> What is the reason to be STOP instead of NONE?

NONE name is vague. It is replaced with STOP since the expected behavior of the vehicle is to keep stopping.

**Pull request merged**
