### PR TITLE
feat(tier4_simulation_msgs): add traffic light v1 messages

### PR DESCRIPTION
**Pull request by HansRobo**
Signed-off-by: Kotaro Yoshimoto <pythagora.yoshimoto@gmail.com>

## Description

The messages for traffic light was changed not to represent physical traffic lights, in autoware_perception_msgs.
This change made difficult to visualize or do something about physical traffic lights based on Autoware's traffic light topic.

These messages are for  treating physical traffic light instead of old `autoware_auto_perception_msgs`.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yukkysaito** [comment]
Which specific types of autoware_auto_msgs are you referring to?
The migration list is written here:
https://github.com/orgs/autowarefoundation/discussions/3862#discussioncomment-9638820

**Comment by HansRobo** [comment]
@yukkysaito 
Thank you for the comment!

> Which specific types of autoware_auto_msgs are you referring to?

The correspondence with `autoware_auto_msgs` is as follows:
| message in this PR | message in `autoware_auto_msgs` |
| --- | --- |
| `tier4_simulation_msgs/TrafficLightArrayV1` | `autoware_auto_perception_msgs//TrafficSignalArray`
| `tier4_simulation_msgs/TrafficLightV1` | `autoware_auto_perception_msgs//TrafficSignal`
| `tier4_simulation_msgs/TrafficLightBulbV1` | `autoware_auto_perception_msgs//TrafficLight`

> The migration list is written here:

I don't intend to do a migration.
One of the reasons for defining new custom messages is to avoid effects from message changes in Autoware.

**Comment by mitsudome-r** [comment]
I think what @HansRobo is trying to represent with this new message is individual traffic light instead of TrafficLightGroup (which is a group of traffic lights with same behavior). 
Actually, we have [tier4_perception_msgs/TrafficLight](https://github.com/tier4/tier4_autoware_msgs/blob/tier4/universe/tier4_perception_msgs/msg/traffic_light/TrafficLight.msg) to represent this.

**Comment by mitsudome-r** [comment]
Could you also explain if this message will be used to communicate between Autoware and a simulator (e.g., scenario_simulator) or is this just for internal communication within simulator modules?

**Comment by HansRobo** [comment]
> Could you also explain if this message will be used to communicate between Autoware and simulator (e.g., scenario_simulator) or is this just for internal communication within simulator modules?

This message is used for output from ScenarioSimulator to external.
However, it is not intended to be used by Autoware, and is intended specifically for external tools such as Autoware Evalautor.

**Comment by HansRobo** [comment]
> I think what @HansRobo is trying to represent with this new message is individual traffic light instead of TrafficLightGroup (which is a group of traffic lights with same behavior).

exactly.
Furthermore, the added messages are designed so that external tools can properly detect large message changes as type changes, while small constant changes can be handled without requiring tooling changes.

**Comment by yukkysaito** [comment]
@HansRobo Thanks for your reply
What information is missing from the existing TrafficLight?

**Comment by HansRobo** [comment]
@yukkysaito 
> What information is missing from the existing TrafficLight?

The information is sufficient in the existing TrafficLight.
However, the purpose is to provide additional support like described below and to separate the messages.

> Furthermore, the added messages are designed so that external tools can properly detect large message changes as type changes, while small constant changes can be handled without requiring tooling changes.

**Comment by HansRobo** [comment]
@yukkysaito @mitsudome-r 

How should we proceed with this PR?
I understand that there are similar messages, but separating the messages in the first place is meaningful in itself, so for now I'm not considering [tier4_perception_msgs/TrafficLight](https://github.com/tier4/tier4_autoware_msgs/blob/tier4/universe/tier4_perception_msgs/msg/traffic_light/TrafficLight.msg) as an option.

**Comment by HansRobo** [comment]
Note: The visualization of traffic lights on Autoware Evaluator was implemented and released based on these messages.
CC: @vios-fish

**Comment by HansRobo** [comment]
CC: @YoshinoriTsutake

**Comment by HansRobo** [comment]
The messages are moved into scenario_simulator_v2
https://github.com/tier4/scenario_simulator_v2/pull/1262

**Pull request closed without merging**
