### PR TITLE
feat(tier4_rtc_msgs): add new field to rtc cooperate status

### PR DESCRIPTION
**Pull request by satoshi-ota**
## Related Links

[TIER IV INERNAL LINK](https://tier4.atlassian.net/wiki/spaces/~332626662/pages/3086190058/P+C+RTC)

## Description

Add new field `tier4_rtc_msgs/State state` so that external tools (e.g. FOA, MOT) can detect canceled behavior.

image

```
uint8 type

uint8 WAITING_FOR_EXECUTION = 0
uint8 RUNNING = 1
uint8 ABORTING = 2
uint8 SUCCEEDED = 3
uint8 FAILED = 4
```

### Example Usecase

| situation    | state in cooperate status    | FOA    | 
| --- | --- | --- | 
| Detect obstacle on the lane. Avoidance module starts running and publishing cooperate status.   |  `WAITING_FOR_EXECUTION`   |     | 
| Operator approves avoidance RTC request.    |   `RUNNING`  |     | 
| Obstacle has gone. Avoidance maneuver is no longer needed.   | `RUNNING`    |     | 
| Avoidance module reverts avoidance maneuver and cooperate request. | `FAILED` | **Detect state transition to `FAILED` from `RUNNING`. Notify operator of canceling.** |
| Avoidance module stops running. | `FAILED` | |

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yukkysaito** [comment]
Can you draw a diagram of the state transitions, I'd be happy to ask for it in the README or something.

**Comment by satoshi-ota** [comment]
@yukkysaito I adde diagram and example usage. Is it okay for you...?

**Comment by mitsudome-r** [comment]
@satoshi-ota Is the information going to be available in some documentation? No one would want to look for this PR to know the state transition. If its going to be described in FOA/MOT app's README, that's also okay, but I want to put it somewhere more visible.

**Comment by mitsudome-r** [comment]
Also, I thought it might be better to add some comments to explain what each field is used for, just like in [sensor_msgs/Image](https://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/Image.html) message for example because the message is starting to get big and hard to understand the purpose of each fields just from the variable's name.

Something like the following might work (please fix the description since I'm not sure about some of the fields)
```
# module type
tier4_rtc_msgs/Module module

# received command from human operator
tier4_rtc_msgs/Command command_status

# current execution status of RTC module
tier4_rtc_msgs/State state

# Indicates whether Autoware thinks it's safe to execute RTC
bool safe

# Indicates if the module is in auto mode. 
# If true, Autoware will automatically execute RTC behavior without 
# waiting for human operator's command. (i.e., when "safe" field is true)
bool auto_mode

# distances to where RTC will start/finish it's execution
float32 start_distance
float32 finish_distance
```

This is just a suggestion and I'm open to other opinions about how we do this(e.g., explain in a separate README file, do it in a separate PR, etc).

**Comment by satoshi-ota** [comment]
> @satoshi-ota Is the information going to be available in some documentation? No one would want to look for this PR to know the state transition. If its going to be described in FOA/MOT app's README, that's also okay, but I want to put it somewhere more visible.

I'm thinkind I'll put documentation in https://autowarefoundation.github.io/autoware.universe/main/planning/rtc_interface/#rtc-interface.

**Comment by satoshi-ota** [comment]
> Also, I thought it might be better to add some comments to explain what each field is used for, just like in [sensor_msgs/Image](https://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/Image.html) message for example because the message is starting to get big and hard to understand the purpose of each fields just from the variable's name.
> 
> Something like the following might work (please fix the description since I'm not sure about some of the fields)
> 
> ```
> # module type
> tier4_rtc_msgs/Module module
> 
> # received command from human operator
> tier4_rtc_msgs/Command command_status
> 
> # current execution status of RTC module
> tier4_rtc_msgs/State state
> 
> # Indicates whether Autoware thinks it's safe to execute RTC
> bool safe
> 
> # Indicates if the module is in auto mode. 
> # If true, Autoware will automatically execute RTC behavior without 
> # waiting for human operator's command. (i.e., when "safe" field is true)
> bool auto_mode
> 
> # distances to where RTC will start/finish it's execution
> float32 start_distance
> float32 finish_distance
> ```
> 
> This is just a suggestion and I'm open to other opinions about how we do this(e.g., explain in a separate README file, do it in a separate PR, etc).

Thank you for your suggestion. I'll add explanation.

**Comment by satoshi-ota** [comment]
@mitsudome-r I added variable explanation in https://github.com/tier4/tier4_autoware_msgs/pull/119/commits/9e887f0ecbcb930e4715be7c32bb7b204b384e9a.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by mitsudome-r — APPROVED** [review]
LGTM

**Pull request merged**
