### PR TITLE
refactor(tier4_localization_msgs): remove unused depend in packages.xml files

### PR DESCRIPTION
**Pull request by YamatoAndo**
## Related Links
https://github.com/autowarefoundation/autoware.universe/pull/3606

## Description

result of unused.sh (https://github.com/autowarefoundation/autoware/issues/3468)

```
--- Checking src/universe/external/tier4_autoware_msgs/tier4_localization_msgs/package.xml ---
builtin_interfaces seems not to be used
```

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Code is properly formatted
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by YamatoAndo** [comment]
@mitsudome-r @VRichardJP  I noticed [this PR](https://github.com/tier4/tier4_autoware_msgs/pull/85).
Since it is a duplicate, it is okay to close my PR.

**Comment by YamatoAndo** [comment]
@mitsudome-r

**Comment by YamatoAndo** [comment]
@mitsudome-r @mitsudome-r

**Comment by VRichardJP** [comment]
@YamatoAndo
No problem. Mine is a bit old and I don't have much time to follow it up.
Actually if you could take over I would be more than happy ;-)

**Comment by YamatoAndo** [comment]
@VRichardJP OK! I'll take over it!

**Comment by YamatoAndo** [comment]
@mitsudome-r @mitsudome-r @mitsudome-r

**Comment by yukkysaito** [comment]
@YamatoAndo could you resolve conflicts?

**Comment by YamatoAndo** [comment]
@yukkysaito Hi, I have resolved! Thank you!

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
