### PR TITLE
feat(tier4_control_msgs): add pause source field for pause interface improvement

### PR DESCRIPTION
**Pull request by brkay54**
## Related Links

To can be made vehicle paused from other nodes, I improved pause_interface. This message and service files also should be changed.  

https://github.com/autowarefoundation/autoware.universe/pull/2528#issuecomment-1451505558

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by brkay54** [comment]
I can not assign reviewer @kenji-miyake , could you assign someone? 🙏🏼

**Comment by kenji-miyake** [comment]
@yukkysaito @TakaHoribe cc @mitsudome-r I think you guys are the appropriate reviewers. Could you please review this?

**Comment by yukkysaito** [comment]
@mitsudome-r Can you explain this PR at the meeting?

**Comment by mitsudome-r** [comment]
@brkay54 
We had some improvements in emergency handler to achieve moderate braking for predicted path.
Maybe we can have another discussion in the next WG call with @TakaHoribe and @yukkysaito if we can use that system instead of adding new interface.

**Comment by brkay54** [comment]
Hi, @mitsudome-r -san, Are we gonna talk about it today's Software WG?

**Comment by mitsudome-r** [comment]
@brkay54 Let's talk in the Planning/Control meeting this week.
Just as a heads up, I have talked with @isamu-takagi, @yukkysaito, and @TakaHoribe, but we might have to change the approach.

Takagi-san said that he doesn't want to have pause interface used to "decelerate" the vehicle. It is more for make the vehicle stay at stop state. (e.g., like side brake or park gear)
Instead we would like to add another filter in vehicle command gate for moderate stop next to emergency stop as the following:

- Modify vehicle_cmd_gate
  - add `~/moderate_stop` service
  - add parameter `moderate_stop_deceleration`
  - This is similar to emergency stop, but stop with lower deceleration
  - When ever vehicle_cmd_gate receives stop request from moderate_stop topic, then it will overwrite control message using given parameter:
    - velocity = 0
    - acceleration = $moderate_stop_deceleration
- moderate_stop service type:
  - Time stamp
  - bool stop
  - string request_source

**Pull request closed without merging**
