### PR TITLE
feat: first draft proposal implementation for handling invalid lanelets

### PR DESCRIPTION
**Pull request by ahmeddesokyebrahim**
### Discussion
- [Discussion Link](https://github.com/orgs/autowarefoundation/discussions/3275)
### Issue 
- [Issue Link](https://github.com/autowarefoundation/autoware/issues/3308)
### Relevant PRs
  - [autoware_documentation](https://github.com/autowarefoundation/autoware-documentation/pull/337) :heavy_check_mark: 
  - [autoware_common - part I](https://github.com/autowarefoundation/autoware_common/pull/175) :heavy_check_mark: 
  - [autoware_common - part II](https://github.com/autowarefoundation/autoware_common/pull/188) :heavy_check_mark: 
  - [autoware_adapi_msgs](https://github.com/autowarefoundation/autoware_adapi_msgs/pull/27) :heavy_check_mark:
  - [autoware_launch](https://github.com/autowarefoundation/autoware_launch/pull/235) :heavy_check_mark:
  - [autoware_universe - part I](https://github.com/autowarefoundation/autoware.universe/pull/3000) :heavy_check_mark:
  - [autoware_universe - part II](https://github.com/autowarefoundation/autoware.universe/pull/3967) :heavy_check_mark:
  - [tier4/tier4_autoware_msgs - part II](https://github.com/tier4/tier4_autoware_msgs/pull/87) :heavy_check_mark:
  - ~[tier4/tier4_ad_api_adaptor](https://github.com/tier4/tier4_ad_api_adaptor/pull/95)~

## Notes for reviewers
For compiling and testing this PR, all PRs in related links section need to be taken into consideration.

## Notes for reviewers

For compiling and testing this PR, all PRs in related links section need to be taken into consideration.

:exclamation: **Merge sequence can be found [here](https://github.com/orgs/autowarefoundation/discussions/3275#discussioncomment-5379038)** :exclamation: 

## Description
This PR is one of group of PRs for providing a solution for the idea discussed [here](https://github.com/orgs/autowarefoundation/discussions/3275).

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by isamu-takagi** [comment]
I think a name that means it is not included in ODD would be better. I could not imagine the background of the discussion from the name INVALID_LANELET.

**Comment by ahmeddesokyebrahim** [comment]
> I think a name that means it is not included in ODD would be better. I could not imagine the background of the discussion from the name INVALID_LANELET.

Thanks Mr @isamu-takagi  for your comment.

When I presented this [idea](https://github.com/orgs/autowarefoundation/discussions/3275) first time at ASWG, I was proposing it as  `invalid or out of ODD` as mentioned in the discussion. During the meeting some colleagues commented that the naming of out of ODD is very wide and may include a lot of meanings. ODD may include road types, driving scenario types, speed limits, weather condition, .... any many other examples. 

That is went for naming with `invalid` rather than `out of ODD` .

**Comment by isamu-takagi** [comment]
>That is went for naming with invalid rather than out of ODD .

@ahmeddesokyebrahim 
I got it. It's fine If agreed in the ASWG, but personally I get the impression that it's detected an error in the lanelet map definition.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by mitsudome-r — APPROVED** [review]

**Pull request merged**
