### PR TITLE
feat(tier4_external_api_msgs): add bagtaker messages.

### PR DESCRIPTION
**Pull request by tsugi1203**
## Related Links

https://tier4.atlassian.net/wiki/spaces/T4DC/pages/2479522726/bagtaker
https://tier4.atlassian.net/wiki/spaces/T4DC/pages/2476605764/GUI#%E2%9A%99%E8%A8%AD%E8%A8%88
https://tier4.atlassian.net/browse/T4PB-12283
https://tier4.atlassian.net/wiki/spaces/SI/pages/2470576470/2022-07-08+bagpacker+rosbag

## Description

Add the Bagtaker service messages to the tier4_external_api_msgs for copying the rosbag logs to the external storage device.
added service messages: RosbagCopyList.srv, StartRosbagCopy.srv
added topic message: RosbagCopyStatus.msg

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [x] All open points are addressed and tracked via issues or tickets
- [x] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by yabuta — APPROVED** [review]
LGTM

**Comment by yabuta** [comment]
@ito-san @0x126 動作的に問題なかったのと影響はbagtakerにしかないので入れてしまっても良さそうです
何かコメントなどあればお願いします

**Review by ito-san — APPROVED** [review]
LGTM

**Comment by yabuta** [comment]
リリースノート追加してなかったので追加しました
https://tier4.atlassian.net/wiki/spaces/AIP/pages/2473561308/WIP+autoware.universe+v0.6.0+Release+Notes#msg-%3A-bagtaker%E7%94%A8%E3%81%AEmsg-type%E3%81%AE%E8%BF%BD%E5%8A%A0

**Pull request merged**
