### PR TITLE
feat: add auto mode status

### PR DESCRIPTION
**Pull request by taikitanaka3**
## Description

add auto mode status
Screenshot from 2022-12-18 12-37-51

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code is properly formatted
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code is properly formatted
- [x] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by tkimura4 — APPROVED** [review]
LGTM

**Comment by taikitanaka3** [comment]
fail ci for galactic unique_identifier_msgs depends?

**Comment by taikitanaka3** [comment]
@kenji-miyake 
Do you know how to add --include-eol-distros to this repository workflow?

**Comment by kenji-miyake** [comment]
@taikitanaka3 cc @tkimura4 I know it, but before that, please consider whether we really need Galactic support for this repository.
If not, let's merge https://github.com/tier4/tier4_autoware_msgs/pull/52 and change the required condition.

**Comment by taikitanaka3** [comment]
I think build is checked by humble version, so.ci build for galactic is not necessary as requirement, but i want ci fix galactic version build testing.

**Comment by kenji-miyake** [comment]
For now, I've disabled the Galactic build from the required condition.

**Pull request merged**
